### ISSUE TITLE
Compilation tries to assign stdout/stderr to a macro

### ISSUE THREAD

**Issue by manveru** [zimmski/osutil#8]
`go get -v github.com/zimmski/osutil` gives following output:

    go get -v github.com/zimmski/osutil
    github.com/zimmski/osutil
    # github.com/zimmski/osutil
    ../../../github.com/zimmski/osutil/capture.go:79: cannot assign to _Cmacro_stderr()
    ../../../github.com/zimmski/osutil/capture.go:79: cannot assign to _Cmacro_stdout()
    ../../../github.com/zimmski/osutil/capture.go:103: cannot assign to _Cmacro_stderr()
    ../../../github.com/zimmski/osutil/capture.go:103: cannot assign to _Cmacro_stdout()

Any ideas what might be wrong here?

**Comment by zimmski** [comment]
Can you do a `go env`?

**Comment by manveru** [comment]
GOARCH="amd64"
    GOBIN=""
    GOCACHE="/home/manveru/.cache/go-build"
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/home/manveru/go"
    GORACE=""
    GOROOT="/nix/store/hvkjn72g4r6pvjgqhjmj98lmpk82xm23-go-1.10/share/go"
    GOTMPDIR=""
    GOTOOLDIR="/nix/store/hvkjn72g4r6pvjgqhjmj98lmpk82xm23-go-1.10/share/go/pkg/tool/linux_amd64"
    GCCGO="gccgo"
    CC="gcc"
    CXX="g++"
    CGO_ENABLED="1"
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"
    PKG_CONFIG="pkg-config"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/run/user/1000/go-build217879405=/tmp/go-build -gno-record-gcc-switches"

**Comment by manveru** [comment]
Any ideas how to debug this?

**Comment by oberg-s** [comment]
It seems to be a compatibility issue with golang >= 1.10?  I don't get the error from a docker golang 1.9 image.
```
$ docker run -it --rm --name test-go-get-osutil golang:1.9
Unable to find image 'golang:1.9' locally
1.9: Pulling from library/golang
...
Digest: sha256:60acff4ca0f1699deab4717cae52bd6c8163cc0e86e9322e1aed5cb70f718081
Status: Downloaded newer image for golang:1.9
root@b882628e9840:/go# go get -v github.com/zimmski/osutil
github.com/zimmski/osutil (download)
github.com/stretchr/testify (download)
github.com/stretchr/testify/vendor/github.com/davecgh/go-spew/spew
github.com/stretchr/testify/vendor/github.com/pmezard/go-difflib/difflib
github.com/stretchr/testify/assert
github.com/zimmski/osutil
```
```
$ docker run -it --rm --name test-go-get-osutil golang:1.10
Unable to find image 'golang:1.10' locally
1.10: Pulling from library/golang
Digest: sha256:62b42efa7bbd7efe429c43e4a1901f26fe3728b4603cb802248fff0a898b4825
Status: Downloaded newer image for golang:1.10
root@0ec6833b8052:/go# go get -v github.com/zimmski/osutil
github.com/zimmski/osutil (download)
github.com/stretchr/testify (download)
github.com/stretchr/testify/vendor/github.com/pmezard/go-difflib/difflib
github.com/stretchr/testify/vendor/github.com/davecgh/go-spew/spew
github.com/stretchr/testify/assert
github.com/zimmski/osutil
# github.com/zimmski/osutil
src/github.com/zimmski/osutil/capture.go:79: cannot assign to _Cmacro_stderr()
src/github.com/zimmski/osutil/capture.go:79: cannot assign to _Cmacro_stdout()
src/github.com/zimmski/osutil/capture.go:103: cannot assign to _Cmacro_stderr()
src/github.com/zimmski/osutil/capture.go:103: cannot assign to _Cmacro_stdout()
```

**Comment by manveru** [comment]
Thanks, that was the issue. Hopefully we'll get a new version sometime :)

**Comment by prestonvanloon** [comment]
https://github.com/golang/go/issues/25221
